### ISSUE TITLE
Umbrel instructions outdated

### ISSUE THREAD

**Issue by beinardus** [beinardus/lnd-fee-manager#2]
Latest release of Umbrel (umbrelOS 1.4.2) no longer uses the scripts to install apps and the directory structure seems to be (slightly) changed. Current workaround is by setting up the environment settings in an `.env` file:

```env title=".env"
APP_LND_FEE_MANAGER_ROOT=/home/umbrel/umbrel/app-data/lnd-fee-manager
APP_LIGHTNING_NODE_DATA_DIR=/home/umbrel/umbrel/app-data/lightning/data/lnd
LND_IP=10.21.21.9
LND_GRPC_PORT=10009
```

And running `lnd-fee-manager` in the Umbrel default network to get access to gRPC (not yet figured out why this is needed)

```yaml title="docker-compose.yml"
services:
  lnd-fee-manager:
    image: lnd-fee-manager
    build: ${APP_LND_FEE_MANAGER_ROOT}/
    container_name: lnd-fee-manager
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_LND_FEE_MANAGER_ROOT}/data:/app
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/home/charge/.lnd:ro
    environment:
      - DATABASE_PATH=/app/database.db
      - GRPC_LOCATION=${LND_IP}:${LND_GRPC_PORT}
      - MACAROON_PATH=/home/charge/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
      - TLS_CERT_PATH=/home/charge/.lnd/tls.cert
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
```

Then just run `docker compose up -d`

Final fix should be to set up an installation directory in github customized for Umbrel, so it can be installed using something like:
```bash
umbreld client apps.install.mutate \
  --repo "https://github.com/beinardus/lnd-fee-manager" \
  --ref main
```
